live_config_reload = true

[font]
size = 16

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[keyboard]
bindings = [
{key = "T", chars = "\u0013c", mods = "Command"},
{key = "J", chars = "\u0013T", mods = "Command"},
{key = "W", chars = "\u0013x", mods = "Command"},
]

[window]
decorations = "buttonless"
dynamic_padding = false
dynamic_title = true
opacity = 0.85

[window.padding]
x = 18
y = 16
